"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['games.db', 'assets/images/bB.png','assets/images/bK.png','assets/images/bN.png','assets/images/bP.png','assets/images/bQ.png','assets/images/bR.png','assets/images/wB.png','assets/images/wK.png','assets/images/wN.png','assets/images/wP.png','assets/images/wQ.png','assets/images/wR.png']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
